### ISSUE TITLE
Mapping the Metaverse - a Cross-Industry Leadership from OMI

### ISSUE THREAD

**Issue by LightLodges** [omigroup/omigroup#109]
# Metaverse Mapping

## Contributors

- Evo, Co-Chair
- Article by Doug Thompson: https://outofscope.bureauofbrightideas.com/a-map-of-the-metaverse/

## Summary

Dynamic map of the metaverse industry with a clear assessment toward interoperability

## Example Use Cases

Dynamic maps exist of other fields, such as the cloud industry: 

## Implementation

1. Begin conceptualizing how to pull 2D field maps into a 3D industry map (needs assessment, iconography, how to map?)
2. Address best use of dynamic database/dataviz tools native for 3D web
3. Set dates to hack together a mapping process (proposed November 12-Thansgiving week)
4. Let the dust settle, fix issues, edit and bring to community  (Dec 1-5)
5. Open for public participation, include public engagement as part of OMI end of year community membership drive

**Comment by robertlong** [comment]
Links from OMI meeting 26:

Possible React Three Fiber library to use for 3D visualization

https://twitter.com/flavioschneide/status/1450792815240351749

From @madjin

![image](https://user-images.githubusercontent.com/1753624/138135263-c3f9d057-ce1c-43ed-83d2-c533d7dc1685.png)

https://hackmd.io/@XR/maps

Notes:
- Concern around how you would be included in this map
- "It could be a map of types of interoperability, where anyone can add themselves to a type" - Koolala
- Filters for viewing different categories (ex. enterprise, AR, etc.)

**Comment by LightLodges** [comment]
Questions to sort out:

What are the branches/flavors of interoperability that people could add themselves to as part of this dynamic map?

Best methods for 3D mapping with participation potential

Github -> Miro for v1 collaboration starting October to gather these elements?

Iconography for needs assessment - Kavya at XRSI recommended we consider using https://cyberxr.org/responsible-innovation-principles-in-immersive-technology/ as they have accepted iconography that may help on needs assessment in a way that compliments the tentpole interop issues of OMI. Thoughts on ways to simplify/use this iconography as it relates to identity, safety, privacy, accessibility, inclusivity, portability, addressability and other interop goals?

**Comment by Elirudite** [comment]
Upon further thought on this, I really think it would be great to approach this project from the idea of creating 'map making tools' as opposed to any definitive map. 

Looking at OMI's mission/values, as well as the great considerations brought up in the call and across Twitter to folks who responded to Doug's article, becoming the 'definitive map' leaves this way too open to potentially becoming a gatekeeper as opposed to a bridge builder. 

I do think gatekeepers are actually necessary to ensure quality and safety (like if we want to have a 'preferred vendors' list of platforms that are interoperable, open, and inclusive that could be a good reason to 'gatekeep'). However, our main mission is indeed to bridge virtual worlds.

So perhaps we can figure out ways to enable people to build their own 'maps of the metaverse' that we also can keep records of. 

For the hackathon, I'd love to see different levels of tools or different teams tackling this from different perspectives. 
These map-making tools can be things like:

- Simple 'drag and drop' (2D or 3D) grids where non-technical people can place icons/portals/images of worlds + draw connections between them.
- Geotagging to map physical hotspots for communities (like a heatmap of where users are based on the general location they are comfortable sharing) for those who want to see how these communities map with the real world, can also be used for outages, server ping, etc
- Metadata-rich mapping allowing developers to see and navigate worlds based on various technical aspects (supported protocols, available APIs, device integrations, etc)
- Accessibility-friendly mapping that audits different levels and types of accessibility (AA vs AAA, blind vs deaf, low-tech devices vs high-tech devices, etc)
- Blockchain-based map (like M3's 'silk road metaphor) for worlds partaking in inter-verse trade (or inter-world? inter-platform?)

There's probably many more, but as you can see, by taking this approach, we can position ourselves to constantly maintain our mission to bridge virtual worlds in different ways, and follow all of our core principles. We can also sidestep the problem of becoming some kind of centralized arbiter of truth, and instead empower the community however we can.

**Comment by PeterCorless** [comment]
There needs to be different levels of "map making":

- "Physical" mapping in a 3D space within a region of a metaverse (what is your local coordinate system?) — what is your locus, and how do you fix 'place' [simple XYZ? planetary coordinates? interstellar coordinates?] Routing & pathing needs to be done in context of the local region ("as the crow flies" vs. virtual transportation methods that might include teleportation, or may have more circuitous routes — obstructions in a virtual city)
- Logical mapping of metaverse regions in relation to each other, including definitions of boundaries and gateways. These should include routing & pathing algorithms — what is the quickest way to get from metaverse region A, coordinate X, to metaverse region B, coordinate Y?
- Metaversal instantiation to real-world mapping. Because this may include how data is segregated over regional and national borders, thus affecting data governance and localization, as well as technical issues of user routing to a localized metaversal node for load balancing, and/or network latency.

So any proposal needs to deal with all three types of "mapping." And forgive me, I may not have given sufficient attention to other issues, such as inter-entity routing. For example, what if a metaversal region is run by organization Alpha, and they want to avoid traversing organization Beta's region? Either due to security policy, cost or some other issue?

**Comment by PeterCorless** [comment]
Also, there's going to have to be regional "mapping-mapping." By which I mean, for example, let's pretend that you want to take a slice of Midtown Manhattan for your metaversal region. You don't want people to have to do actual planetary coordinates — which require trigonometry to really do "right." You're instead going to give them simple XYZ coordinates to plop down buildings and street signs. But you may want to have a mapping between that simple XYZ and a more realistic planetary coordinate system, so that the chunk of the local region can eventually be placed on a broader city map as well as the planetary surface.

**Comment by technobaboo** [comment]
I think the best way to do this is to ask the BuildTheEarth people who have had to do exactly this for Minecraft with the Terra1:1 mod. They chose dymaxion projection and had a teleport command for global coordinates.

**Comment by madjin** [comment]
Experiments with memory palaces / virtual production set design / metadata

Made a node (group of objects) in Anarchy Arcade (free on steam) of the [maps dev log](https://hackmd.io/@xr/maps). Basically can drag n drop into that box area and hit the lever to save a node.
![image](https://user-images.githubusercontent.com/32600939/139788954-a63f108e-7ebb-401c-8b70-17c00f5634c9.png)

I can now spawn it in any map and then spatialize each piece. Can drag n drop stuff into program also, will spawn in world (won't save to that node though).
![](https://gyazo.com/199487178236bd5d79bfe9e6b006f4b9.gif)

We can use AArcade to do virtual productions with livestreams, no need to download anything the avatar livestream can be served through web app and composited together in twitch stream. Sets can expand the context of the media presented and talked about. 
![image](https://user-images.githubusercontent.com/32600939/139789283-3634a383-1a8a-4538-a2a9-8a334c1448da.png)

It's possible to export metadata out of AArcade and since SMSithLord modeled most of the assets himself so we can potentially display with arcade mode too. The assets aren't uploaded anywhere public yet.
![image](https://user-images.githubusercontent.com/32600939/139789745-d2559356-ccc0-45cf-82b4-0a863a95f33f.png)

I'm planning to spatialize all of [xrdevlog](https://xrdevlog.com) over a more long term, in meantime down to make some content about this stuff with peeps.

**Comment by PeterCorless** [comment]
I'd hope that we can move from specific instances of how someone is doing something to general rules/protocols for how anyone can do something. For example, you might want to look at GeoJSON to map lat/long to Earth (or digital twin Earth) coordinates. It might be necessary to expand upon this to create artificial worlds with their own planetary geometries (different sizes of planets, different shaped planets, etc.). 

https://datatracker.ietf.org/doc/html/rfc7946

And again, there needs to be a way to go from "flat" XYZ coordinates to "spherical" planetary style lat/long/alt coordinates. ([This particular thread ](https://gis.stackexchange.com/questions/181100/geojson-data-and-xyz-meter-coordinates?rq=1)was interesting.]

**Comment by PeterCorless** [comment]
Is there any proposal on the table as to how partition or divide a metaverse into regions? Or how to define namespaces or addresses to regions of a metaverse? Or to denote statues (e.g., development, test, staging, production) or versioning of a region?

Or is this an area of specific research that should be conducted? (Look at prior art, solicit RFPs, etc.)

**Comment by mrmetaverse** [comment]
Have we looked at what Bai did in 2016? Looks like a great visualization format: 

https://twitter.com/bai0/status/694494970737065985?t=aBeDKzXdo0YPIk_6L7LekA&s=19

![Screenshot_20211117-073531.png](https://user-images.githubusercontent.com/63426722/142201739-7cacd5f1-de3a-4cc4-95a3-7cc3867b48b5.png)

**Comment by mrmetaverse** [comment]
HACKMD from yesterday: https://hackmd.io/w_sUTgcpRcSKdN6Torl-WA?both

**Comment by mrmetaverse** [comment]
discussed the power of gathering the data, rather than focusing on the UI, as anyone could harness the data into different UI/Visualizations as needed 
Proposed wikipedia model 
Be careful not to create second class citizens, or bias 
Would it be acceptable for non-platform-owners to participate in this?

**Comment by technobaboo** [comment]
yes, non platform owners should be able to participate given they can
provide citations for their data

**Comment by mrmetaverse** [comment]
There is a new Miro floating around. Jin is hosting another discussion this week. @madjin @LightLodges can you add relevant links to this tickets comments? 

https://github.com/omigroup/omigroup/issues/109

**Comment by mrmetaverse** [comment]
Updates from grooming: 
- some interest in incubating efforts with us or collaborating on efforts with us 
- possible funding lines from OpenMetaDao, and others like MAD DAO 
- building public-private partnerships including some philanthropic, DAO investments, etc. 
- possible consortium building 
- would like to hear others thoughts on how to approach this problem as a group.

**Comment by mrmetaverse** [comment]
I am putting this in writing to hold myself accountable: 

I am interested in pursuing this full time :point_up_2: the only hold up is that I get Evo and others a pitch deck as promised. Thats it. I am going to tackle that in the next 2 weeks.

**Comment by PeterCorless** [comment]
I had asked a question back in November and it seems to have gone unanswered. What is the status of an actual proposed protocol, standard, formats, coordinate systems or APIs to define metaverse mapping and interoperation?

- Basic Cartesian coordinates ("X/Y/Z" virtual spaces)
- Planetary coordinate systems (degrees of latitude/longitude/altitude)
- Inter-coordinate or inter projection system mapping (i.e., how to turn a virtual lat/long into an XYZ coordinate if you needed to change projections)
- Pathing/routing/gateway methods — how to connect different metaverse spaces together
- Access control/authorization methods — how to say who gets into a metaverse space, and their limitations of participation (view only, comment/intercommunicate, edit, delete, etc.)

I'm looking for actual specifications. Something more than simple conceptualizations.

**Comment by mrmetaverse** [comment]
ARCHIVE
