### ISSUE TITLE
Proposed Portals Working Group

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#209]
# Group Title

I propose that we consider forming a working group for the discovery, experimentation, and delivery of protocols enabling portals in the Metaverse. This group would focus on bridging worlds in creative and open ways. Users should be able to traverse from one World to another, in different platforms. 

This work would take on various levels of fidelity. For example, we may want to explore taking the same avatar to different worlds. We may want to explore what the UX or UI of traversing worlds may look like. We may want to partner with other groups exploring these things as well.

**Comment by limbofeather** [comment]
Thanks @mrmetaverse for getting us started on this proposal!

For now I'll focus more on portals between WebXR apps/platforms, and will leave it open for others to add colour for mobile and desktop. Also thanks to @msub2 for bringing [this](https://lists.w3.org/Archives/Public/www-archive/2022Apr/att-0003/XR_Navigation_thoughts.pdf) to my attention, which is the thinking that came up from the recent WebXR face-to-face meeting in SF last week.

In light of new XR hardware and by assuming an optimistic rate of adoption, I believe that we're headed to a future where people will be creating more 3D webspaces than 2D websites.

In order to support the discovery of new webspaces and to facilitate traversal across them, we need portals that:
* clearly show where the user is going,
* are permissioned by the webspace owner to be placed in a particular location, and, 
* allow for financial agreements to be made to pay for the use of the portal

Whether these financial contracts are made on a blockchain or not is something that can also be in the purview of this working group.

Today, I believe that portals can act as a way to educate XR users of the multitude of creations and experiences that can be had from within a browser context. I believe that there is a general misconception that VR games are only playable inside native Unity/Unreal apps, but this is not the case, as you can see in the _many_ WebXR-compatible platforms on this list: https://github.com/limbofeather/worlds 

(Much thanks to the community for helping populate the above list with names and providing more ideas for a suitable taxonomy.)

With the open-source work happening at [Zesty](https://app.zesty.market) and the progress being made with the adoption of the open [SDK](https://github.com/zestymarket/sdk), there is a unique opportunity to experiment with various ideas of what a portal can look like. 

With currently over 100k visitors to the Zesty portals/billboards each week, the working group can also make sure other WebXR-compatible platforms have a way to be discovered properly.

The Zesty team has been making efforts to shine a light on various immersive worlds, with the most recent one being when users on [Construct Arcade](https://constructarcade.com) could portal out to [vrland.io](https://vrland.io) through a rented billboard/portal on a game called Archery Dungeon. To see what this looked like, you can see this [tweet](https://twitter.com/zestymarket/status/1519008300251201537?s=20&t=_TzIK7dk-Dw75ThOnB0w7A). The space was rented by the creator of vrland.io, @arpu.

Zesty has been also renting out its own spaces to link metaverse travellers to curation sites that collect and display interesting WebXR content, such as [Extended Collection](https://extendedcollection.com/), managed by [Joseph Simpson](https://twitter.com/vrhermit). You can see the Zesty campaigns for it [here](https://app.zesty.market/campaigns/202) and [here](https://app.zesty.market/campaigns/201).

I'm excited to work on this with whoever else may be interested. Appreciate you taking the time to read and I'm happy to answer any questions or comments.

**Comment by powersimple** [comment]
Here are all the playlists for the MetaTr@versal series chaired by Evo Heyning.
https://www.youtube.com/channel/UCBRnEdbmKvanvN8rtfnzApw/playlists

**Comment by mrmetaverse** [comment]
relevant
https://github.com/omigroup/omigroup/issues/238

**Comment by mrmetaverse** [comment]
Not sure if we have the bandwidth, but there is interest. I will propose for review this or next week.

**Comment by mrmetaverse** [comment]
This has taken a step forward today. #356 was proposed, and #omi-portals-pro-tem kicked off today.

**Comment by mrmetaverse** [comment]
is this part of omi-experiments?
